### ISSUE TITLE
[RFE] gadgets/dns: Enhance gadget to provide more information about failed requests and latency

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1196]
This is a follow-up to #1000.

## Current situation

The DNS trace gadget provides information about DNS requests. It provides the following:

- node, namespace, pod: pod where the request is coming from / to
- pktType: direction of the request (ONGOING / INCOMING)
- qtype: type of request
- name: host of the request
- nameserver: DNS server where the request is going to (added in #1071)
- id: to match queries & responses  (added in #1071)

There is more information we could add to this:
- [x] timestamp: when the packet was observed
  - #1206
  - #1205
- [x] latency: time difference between a request and a response by matching the id
- [x] failed requests: we can see responses but we don't know if there is an error, nxdomain or timeout
  - #1217 
- [x] #1415 

## Impact

This makes the dns gadget less useful to debug.

## Ideal future situation

The dns gadget displays the additional information listed above.

**Comment by alban** [comment]
>  latency: time difference between a request and a response by matching the id

I am not sure if matching the dns id field between the dns request and response should be done in ebpf or in the pkg/gadgets/trace/dns/tracer Golang package but I think we should avoid doing it in the CLI to ensure it has a consistent result regardless of the client (kubectl-gadget, local-gadget, Headlamp plugin...).

The dns ids should be forgotten after a timeout or a maximum to ensure that the memory used to track it cannot grow without limits.
* If the timeout is implemented in ebpf, we could use the [bpf timers](https://github.com/torvalds/linux/commit/b00628b1c7d595ae5b544e059c27b1f5828314b4) but this requires Linux 5.15. 
* Alternatively, we could have a ticker in Golang to remove old entries. This could be done in one syscall with a bpf iterator (Linux 5.8).
* This could also be done with a LRU hash (Linux 4.10). Maybe the easiest and most compatible with older Linux versions?

**Comment by alban** [comment]
@wedaly would like to work on this (see https://github.com/inspektor-gadget/inspektor-gadget/pull/1206#issuecomment-1357781484). It seems I can't update the "assignees" field accordingly, so I'm posting a comment here instead.

**Comment by wedaly** [comment]
While working on "failed requests", I noticed that the response code flag wasn't being set correctly. I opened a PR that I think should address that issue: https://github.com/inspektor-gadget/inspektor-gadget/pull/1212

**Comment by mauriciovasquezbernal** [comment]
@alban @wedaly do you think this gadget should report something when there is not an answer to a request? I'm wondering if this is something that the tool ingesting the data generated by this gadget should do.

**Comment by alban** [comment]
> @alban @wedaly do you think this gadget should report something when there is not an answer to a request? I'm wondering if this is something that the tool ingesting the data generated by this gadget should do. 

In general I agree, except if we implement Prometheus metrics, then that's not something that Prometheus can do because the metrics will not be labelled with enough data to correlate queries and responses.

**Comment by wedaly** [comment]
> @alban @wedaly do you think this gadget should report something when there is not an answer to a request? I'm wondering if this is something that the tool ingesting the data generated by this gadget should do.

I think it would be tricky to detect "missing" answers in the gadget itself, because (1) the LRU cache of prior requests may have evicted the question, so we may generate false positives, and (2) the gadget would need to emit an event that isn't necessarily triggered by an incoming DNS packet.

If I were trying to use this tool to detect errors in production, I think I'd either post-process the output (can visually see in the table output that there are queries without answers, or use the JSON output and run a script to find unmatched queries). For Prometheus monitoring, I'd imagine you could get pretty far comparing counts of questions and answers and alerting if there are N% more questions than answers.

**Comment by mauriciovasquezbernal** [comment]
Thanks for the replies. Then I think we should **not** implement a mechanism that detects missing replies on Inspektor Gadget.

**Comment by blanquicet** [comment]
> In general I agree, except if we implement Prometheus metrics, then that's not something that Prometheus can do because the metrics will not be labelled with enough data to correlate queries and responses.
> 
@alban Sorry, I'm not sure I understood. You are saying you agree to report a missing response except if we implement Prometheus. But then you said that Prometheus won't be able to correlate queries and responses because of a lack of information. Sorry but I'm confused 😅. Probably, I misunderstood what you meant.

> I think it would be tricky to detect "missing" answers in the gadget itself, because (1) the LRU cache of prior requests may have evicted the question, so we may generate false positives
> 
@wedaly This can be managed in the gadget. For instance, by creating the LRU cache with an evicted callback, and then storing the ID of the evicted queries so that we don't generate false positives for those ones.

BTW, I think we should print a warning message indicating that a request (indicating also the ID if we use the evicted callback) was evicted from the cache, thus when its response will arrive (if it arrives), the gadget won't be able compute the latency. To compensate, we should make the cache size configurable, something like `--cache-size`. WDYT?

> (2) the gadget would need to emit an event that isn't necessarily triggered by an incoming DNS packet.
>
Why is it a problem?

> If I were trying to use this tool to detect errors in production, I think I'd either post-process the output (can visually see in the table output that there are queries without answers, or use the JSON output and run a script to find unmatched queries). 
>
I see Inspektor Gadget as a tool that provides "raw" data, and it is up to the users to process it as they need. However, if we have a well-known use-case, why make users do all this post-processing if we can "easily" do it for them?

> For Prometheus monitoring, I'd imagine you could get pretty far comparing counts of questions and answers and alerting if there are N% more questions than answers
>
Mmmm let's consider this situation. When the gadget starts, it might receive responses for queries executed before it starts. In such a case, Prometheus would report a false positive. The most accurate way to do this is by using the IDs.

@mauriciovasquezbernal I'm more for implementing a mechanism that detects missing responses in Inspektor Gadget as I think it is a well-known use case. In addition, it is more complicated to be implemented by higher-level tools as they should have to process a lot of data (might probably be very costly), or they will not have enough information to do it (e.g. Prometheus). 

Regarding a possible implementation in Inspektor Gadget, I'm worried about:

1. The timeout we would use to determine that a response didn't arrive. We could probably just use the same value more popular libraries use.
2. I suppose we should keep a timer for each request, so what about the performance? We would probably re-use the latency cache, so things would be limited. However, we should test its performance working at that limit.

WDYT?

**Comment by wedaly** [comment]
> @wedaly This can be managed in the gadget. For instance, by creating the LRU cache with an evicted callback, and then storing the ID of the evicted queries so that we don't generate false positives for those ones.

The motivation for the LRU cache was to bound memory usage if there were many queries without answers, which I think we'd lose if we started storing the evicted entries. Maybe it's worth revisiting the LRU cache eviction strategy? An alternative would be to have a background thread garbage-collect entries with timestamps older than some threshold. Every entry that gets GC'd could be reported as a "missing answer" event.

> BTW, I think we should print a warning message indicating that a request (indicating also the ID if we use the evicted callback) was evicted from the cache, thus when its response will arrive (if it arrives), the gadget won't be able compute the latency. To compensate, we should make the cache size configurable, something like `--cache-size`. WDYT?

Makes sense to me!

> > (2) the gadget would need to emit an event that isn't necessarily triggered by an incoming DNS packet.
> 
> Why is it a problem?

I was remembering that `network/tracer` transformed and output events received from a perf buffer, so I thought it might be difficult to adapt that to output events based on other triggers. I think that code has changed since I last looked, though, so maybe it's easier now.

> Mmmm let's consider this situation. When the gadget starts, it might receive responses for queries executed before it starts. In such a case, Prometheus would report a false positive. The most accurate way to do this is by using the IDs.

That's a fair point. I'm not sure "accurate" is the term I'd use to describe most Prometheus data I've worked with, so maybe I set my expectations too low :)

One thing to clarify -- which maybe is already obvious, but want to make sure -- is that Prometheus considers each distinct set of labels a separate time-series, and it falls over if it scrapes too many time-series. So I think IG could calculate a "missed answer count" metric (based on matching question/answer IDs) without exposing the actual IDs to Prometheus.

**Comment by blanquicet** [comment]
> The motivation for the LRU cache was to bound memory usage if there were many queries without answers, which I think we'd lose if we started storing the evicted entries. 
>
Oops, you are right. I missed completely the point of the LRU cache hahahaha 😅 

> Maybe it's worth revisiting the LRU cache eviction strategy? An alternative would be to have a background thread garbage-collect entries with timestamps older than some threshold. Every entry that gets GC'd could be reported as a "missing answer" event.
>
That's a very interesting idea! I like it. We could have just one timer that every X seconds garbage-collects entries (probably X = 1).

> I was remembering that `network/tracer` transformed and output events received from a perf buffer, so I thought it might be difficult to adapt that to output events based on other triggers. I think that code has changed since I last looked, though, so maybe it's easier now.
>
With the refactoring we are finishing with https://github.com/inspektor-gadget/inspektor-gadget/pull/1396. We can sent events whenever we want.

> I'm not sure "accurate" is the term I'd use to describe most Prometheus data I've worked with, so maybe I set my expectations too low :)

😝 

> So I think IG could calculate a "missed answer count" metric (based on matching question/answer IDs) without exposing the actual IDs to Prometheus.
>
Exactly, I was considering something like that 💯 !

@wedaly Thanks a lot for this exchange of ideas!

**Comment by mauriciovasquezbernal** [comment]
I think such mechanism can work fine. If we want to report missing replies, we should make the tiemout configurable so the user can tune it according to different situations.

**Comment by mauriciovasquezbernal** [comment]
I opened a new issue to continue the discussion about reporting missing answers https://github.com/inspektor-gadget/inspektor-gadget/issues/1512. I'll close this one as all the tasks are done.
