### ISSUE TITLE
Implement gadget to inspect tcp retransmissions 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1423]
From #1199

Implement a new gadget to trace tcp retransmission events. BCC has a tcpretrans tool (https://github.com/iovisor/bcc/blob/master/tools/tcpretrans_example.txt).

**Comment by alban** [comment]
BCC's tcpretrans tool reports events for:
1. TCP retransmissions
  a. with the `tcp/tcp_retransmit_skb` tracepoint when supported (since v4.15, 2018, see https://github.com/torvalds/linux/commit/e086101b150ae8e99e54ab26101ef3835fa9f48d)
  b. with a kprobe on `tcp_retransmit_skb()`
2. TCP TLP (Tail Loss Probe) with a kprobe on `tcp_send_loss_probe()`

I'll initially implement this gadget without TLP support and using the tracepoint (Linux >= v4.15).
