### ISSUE TITLE
Design support for Prometheus metrics

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1513]
Part of https://github.com/inspektor-gadget/inspektor-gadget/issues/1405

The scope of this issue is discuss and design the solution for supporting Prometheus metrics in Inspektor Gadget. The result should be a design document that covers the following aspects:
- Where to expose the metrics (ig, kubectl-gadget, standalone binary)
- Which metrics to expose? 
  - Make them configurable?
- Labels granularity 

Note: There is a PoC available in https://github.com/inspektor-gadget/inspektor-gadget/pull/1384. The design document could base on that approach or propose something different too.

**Comment by flyth** [comment]
I'm currently extending the first PoC to also add support for counters that are (almost) entirely handled in eBPF and thus providing higher throughput. Basically, it's working also through the operator that hands over an interface to the gadget, which the gadget can then use to register certain metrics and get a per-cpu eBPF array/map in return. The operator then polls the map(s) every interval and exposes the values through the prometheus exporter.

The interface basically looks like:
```
RegisterMetrics([]*Metric)
RegisterMetricsPerNS(nsType, []*Metric)
```

The latter method `RegisterMetricsPerNS()` can use the LocalOperator/KubeOperator to get retrieve container, pod and namespace information and add them as labels.

Open question:

There should probably be a metrics-only mode for gadgets, so that they don't emit events but just provide updates to the counters. How can we add this as generic as possible?

> Part of #1405
> 
> The scope of this issue is discuss and design the solution for supporting Prometheus metrics in Inspektor Gadget. The result should be a design document that covers the following aspects:
> 
> * Where to expose the metrics (ig, kubectl-gadget, standalone binary)

In this case, both ig and gadgettracermanager could both support exporting metrics (not kubectl-gadget, though - should it?).

> * Which metrics to expose?

We should look at different implementations of services (like for example DNS servers) and look at what metrics they collect as a starting point.

>   
>   * Make them configurable?

With the current approach, they are plain gadgets, so configurable just like normal (including filtering etc.).

> * Labels granularity

The `RegisterMetricsPerNS()` adds the usual labels, but if we want to go father than this, we'd need to come up with even more flexible stuff (not handled by my update for now).

> 
> Note: There is a PoC available in #1384. The design document could base on that approach or propose something different too.
