### ISSUE TITLE
[RFE] Performances: snapshot socket gadget

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1611]
## Current situation

The snapshot socket gadget is the slowest one.
See "BenchmarkAllGadgetsWithContainers/container100":
https://inspektor-gadget.github.io/ig-benchmarks/dev/bench/index.html

## Impact

The gadget could fail due to timeout when there are a lot of containers.

## Ideal future situation

It should be fast like other gadgets.

## Implementation options

Use a single bpf iterator:
https://github.com/inspektor-gadget/inspektor-gadget/pull/1597

**Comment by mauriciovasquezbernal** [comment]
As discussed in https://github.com/inspektor-gadget/inspektor-gadget/pull/1597#issuecomment-1543729214, another option is to create the eBPF program once and then run it for each network namespace. It's not the best from a performance point of view but it can help.

Also, I'm wondering if using a binary encoding instead of [Sprintf/Sscanf](https://github.com/inspektor-gadget/inspektor-gadget/blob/a2f11c848fd47a7a36927b45a034a0e58824e402/pkg/gadgets/snapshot/socket/tracer/tracer.go#L149) can improve performance.

**Comment by alban** [comment]
> As discussed in https://github.com/inspektor-gadget/inspektor-gadget/pull/1597#issuecomment-1543729214, another option is to create the eBPF program once and then run it for each network namespace. It's not the best from a performance point of view but it can help.

This is already implemented: the eBPF programs are created once with `openIters` and then reused for each network namespace:
https://github.com/inspektor-gadget/inspektor-gadget/pull/1451
https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/gadgets/snapshot/socket/tracer/tracer.go#L286

> Also, I'm wondering if using a binary encoding instead of [Sprintf/Sscanf](https://github.com/inspektor-gadget/inspektor-gadget/blob/a2f11c848fd47a7a36927b45a034a0e58824e402/pkg/gadgets/snapshot/socket/tracer/tracer.go#L149) can improve performance.

I don't think so: the profiling output in https://github.com/inspektor-gadget/inspektor-gadget/pull/1597#issuecomment-1547600010 gives results unrelated to Sprintf/Sscanf.

I will close this issue since we'll not switch the snapshot socket gadget to a single iterator for open files. That will be a different gadget in https://github.com/inspektor-gadget/inspektor-gadget/pull/1725
