### ISSUE TITLE
`TestTraceNetwork` failing sometimes in CI

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1776]
The test failed a couple of times in https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5323662284/attempts/2#summary-14407553312. 

It seems that some entries are missing the container metadata:

```
{"timestamp":1687275447766044955,"type":"normal","netnsid":4026532224,"uid":0,"gid":0,"pktType":"OUTGOING","proto":"tcp","port":80,"remoteAddr":"10.244.0.12"}
```

It could be related to https://github.com/inspektor-gadget/inspektor-gadget/pull/1630, @alban suggested that "It seems the socket enricher fails sometimes but not always, and only client-side... maybe the sockets map is full? That would explain why it works for nginx because its sockets are created before wget's sockets"

Reported in https://kubernetes.slack.com/archives/CSYL75LF6/p1687274504983709

**Comment by alban** [comment]
In the logs linked above, the `trace network` gadget shows output from both various Kubernetes namespaces:
- test-profile-tcprtt-*
- test-top-tcp-*

This is because the test `TestTraceNetwork` runs in parallel with other tests. This is the `ig` test (and not the `kubectl-gadget` test), so it shows events from all Kubernetes namespaces because it does not have a `-n` filter.

The socket enricher cleans up sockets from the map [5 seconds](https://github.com/inspektor-gadget/inspektor-gadget/blob/53631a7ed2ae0d102bb25b4c839b82701067270a/pkg/gadgets/internal/socketenricher/bpf/sockets-map.bpf.c#L182) after they are deleted. This is checked every [2 seconds](https://github.com/inspektor-gadget/inspektor-gadget/blob/53631a7ed2ae0d102bb25b4c839b82701067270a/pkg/gadgets/internal/socketenricher/tracer.go#L168), so at worst the socket is deleted after `~7` seconds. The sockets map can have [16384 entries](https://github.com/inspektor-gadget/inspektor-gadget/blob/53631a7ed2ae0d102bb25b4c839b82701067270a/pkg/gadgets/internal/socketenricher/bpf/sockets-map.h#L83).

A lot of those tests are running `integration.BusyboxPodRepeatCommand()`, which is running a wget command in a loop: `while true; do %s ; sleep 0.1; done`. Some use the URL `https://kubernetes.default.svc.cluster.local`, and a single wget generates 8 udp requests (it seems each dns request is using a new udp socket) + 1 tcp connections. With an external URL like `https://inspektor-gadget.io` (used in the SNI test), the coredns pod would need to forward the request, so that's more udp sockets.

So before the sockets map is cleaned up, a single test can accumulate `10*5*(8+1)` = 450 entries.

With this calculation, the sockets map would be full with `16384 / 450` = 36 tests running in parallel, or maybe less if the kernel is having other sockets open during the tests.

I don't think we run that many tests in parallel, but maybe that's part of the explanation?

I also see that some entries without container metadata have the same netns as some other connections from the kubelet, so the missing container metadata is not a bug: it is just the host. Nonetheless they don't have the socket enrichment.

Some ideas (but I wouldn't want to implement them before the root cause is more clearly identified):
- increase MAX_SOCKETS=16384 to something bigger
- decrease the 5 seconds delay to 2 seconds. It was added to catch the TCP-FIN packet when the socket was already released
- separate tcp and udp sockets in 2 different maps with different sizes
- separate sockets per network namespaces to ensure a noisy neighbor does not break the socket enricher on unrelated containers

What do you think?

**Comment by mauriciovasquezbernal** [comment]
> I don't think we run that many tests in parallel, but maybe that's part of the explanation?

I agree that we aren't running 36 tests in parallel, however your explanation makes sense. 

> increase MAX_SOCKETS=16384 to something bigger

It seems to me like the most obvious solution.

**Comment by alban** [comment]
@mauriciovasquezbernal should I pick up the task about IPv4/IPv6 `v6only`, or are you working on it?

**Comment by mauriciovasquezbernal** [comment]
> @mauriciovasquezbernal should I pick up the task about IPv4/IPv6 `v6only`, or are you working on it?

Please go ahead. I started investigating this failure last week but got blocked by different CI issues.

**Comment by mauriciovasquezbernal** [comment]
#2358 contains a narrower version of this issue. Will close this one.
