### ISSUE TITLE
advise network-policy: panic: unknown event

### ISSUE THREAD

**Issue by bbigras** [inspektor-gadget/inspektor-gadget#1793]
## Impact

[ 1 sentence detailing the impact this bug is creating for you ]

## Environment and steps to reproduce

k3s on nixos

- `kubectl gadget deploy --image=docker.io/mauriciovasquezbernal/gadget:mauricio-ignore-os-release-error --containerd-socketpath=/run/k3s/containerd/containerd.sock`
- `kubectl gadget advise network-policy monitor -n tpg --output ./networktrace.log`
- `kubectl gadget advise network-policy report --input networktrace.log`

```
panic: unknown event

goroutine 1 [running]:
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).eventToRule(_, {{{{0xc000127f50, 0x3}, {0xc000127f53, 0x3}, {0xc000403470, 0x21}, {0xc000127f60, 0x10}}, 0x176c9f746d194588, ...}, ...})
        github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor/advisor.go:218 +0x47f
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).GeneratePolicies(0xc0000cbc78)
        github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor/advisor.go:334 +0x1085
github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/advise.runNetworkPolicyReport(0x32585e0?, {0x1fe1cbd?, 0x2?, 0x2?})
        github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/advise/network-policy.go:134 +0xb6
github.com/spf13/cobra.(*Command).execute(0x32585e0, {0xc0002edf40, 0x2, 0x2})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x3259160)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/main.go:84 +0x312
```

**Comment by alban** [comment]
Thanks for the report!
I think this is caused by commit 614bc0a3f51d ("Generalize network Endpoints") from #1626 merged last Friday:
```diff
-       RemoteKindOther   RemoteKind = "other"
+       EndpointKindRaw     EndpointKind = "raw"
```

The format of the output changed and I think you use two different versions of IG on the server and client:
- The command "network-policy monitor" generates the json on the server (image deployed: "docker.io/mauriciovasquezbernal/gadget:mauricio-ignore-os-release-error", contains #1626)
- The command "network-policy report" parses the json on the client (kubectl-gadget compiled from a different version, presumably does not contain #1626)

As a workaround, you could run the command "advise network-policy report" from a more recent version of kubectl-gadget (recompiled from the main branch).

I think we should not panic in the CLI and at a minimum report a better error message.

cc @burak-ok @flyth Do you have ideas how to handle different versions between kubectl-gadget and the gadget pod in that case?

**Comment by mauriciovasquezbernal** [comment]
> cc @burak-ok @flyth Do you have ideas how to handle different versions between kubectl-gadget and the gadget pod in that case?

Our [version skew policy](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/install.md#version-skew-policy) requires both components to be the exact same version. I know it's limiting but it avoid us a lot of pain when updating the code. 

 @bbigras the [PR](https://github.com/inspektor-gadget/inspektor-gadget/pull/1788) I was testing on that branch is already merged to main. You can follow the [compile from source](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/install.md#compile-from-source) instructions to get the latest kubectl-gadget version. (You don't need to worry about the container image as we keep the latest version on our container repository).

**Comment by bbigras** [comment]
It works fine with 0.18.1. Thank you very much.
