### ISSUE TITLE
Do not run experimental feature test in the ci

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#1805]
## Description

da18f5b36b0d844120e9da76a6fcdf3b254a26d2 modified Inspektor Gadget deployment in the CI to be able to use experimental features.

## Impact

Using experimental feature leaded to break the CI

## Expected behavior

Testing experimental feature is a good idea, but this should be done in a specific job or pipeline.
This way, having a failing in experimental feature does not prevent us for releasing.

## Additional information

The following needs to be enhanced as we would need to add a flag to integration test to detect which feature are experimental and disable running them when running in the conventional CI:
https://github.com/inspektor-gadget/inspektor-gadget/commit/23eb1347555f1af2d1f2924e09eb8b84d1590ca8

**Comment by mauriciovasquezbernal** [comment]
IMO we should run the experimental features in the normal workflows. Otherwise we'll have to duplicate all jobs and that's too much.

**Comment by mauriciovasquezbernal** [comment]
> First, we had the problem this morning where an experimental feature leaded to some problems in the CI.

This is not related at all with it being an experimental feature or not. We have broken the CI many times with "non-experimental" features, so there's nothing special about them in this regard.

> Then, it is totally fine to have experimental feature, but if we rely on tests testing the experimental features before releasing the stable release it is really strange. In this case, what is the release? A really stable one where even the experimental feature are deemed stable? Then if they are stable they are no more experimental?

Experimental doesn't mean the feature is broken. It's more in the sense it's incomplete and their UX can change in the next iteration. If we have testing for experimental features then they should work fine and be considered as other tests. Otherwise, what are they for?

> No need to duplicate stuff, we can perfectly add some matrix stuff where we have some job to only test experimental feature.

That implies adding extra logic to handle the experimental case in that matrix, which makes the workflow definition even more complicated than it currently is.

**Comment by mauriciovasquezbernal** [comment]
> Or we can run remove the --experimental flag in the CI? Then no more complexity.

But then we won't have the results of tests for experimental features.

> I think we need to come up with a clear definition for experimental and stable

I think that's part of the confusion. I totally agree with your comment, experimental features should work good as other ones and their tests should not be (as far as possible) flaky.
