### ISSUE TITLE
Dns Tracer - Uncompressed Messages Support

### ISSUE THREAD

**Issue by amitschendel** [inspektor-gadget/inspektor-gadget#2008]
## Description

The current dns tracer doesn't show the addresses of dns messages which aren't compressed as mentioned in the tracer docs.
@mauriciovasquezbernal told me to open an issue about it so you have track on it.

## Impact

Limited tracer output.

## Environment and steps to reproduce

Run the dns tracer in a local cluster such as minikube and try to resolve in cluster services.

## Expected behavior

The dns messages will probably be small and therefor coredns won't compress them so we won't see addresses output.

## Additional information

----

**Comment by mauriciovasquezbernal** [comment]
Additional context: It's not supported right now because doing this on eBPF is very difficult. We're in the process of implementing our gadgets as "containerized gadgets" (https://github.com/inspektor-gadget/inspektor-gadget/issues/1929), I think we could support this by using wasm as done in this poc -> https://github.com/inspektor-gadget/inspektor-gadget/pull/1985
