### ISSUE TITLE
[RFE] Update GadgetInfo() rpc to avoid handling BTF/Wasm client-side

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#2131]
## Current situation

I would like to revisit the design decision in this commit:

https://github.com/inspektor-gadget/inspektor-gadget/pull/2015/commits/8b513e713340f35f9b301af6914542d3f6f8abf1

Currently, in the client/server architecture, the client needs to get the columns of a gadget. This is done with the `GetGadgetInfo()` rpc call. Then, the server returns the following struct:
```
type GadgetInfo struct {
	GadgetDefinition *GadgetDefinition
	ProgContent      []byte
}
```

## Impact

`ProgContent` includes the BTF information and the client needs to parse this in order to find the columns. Some special care needs to be taken client-side for the L3Endpoints and L4Endpoints columns.

## Ideal future situation

I think the client should not parse BTF at all.

## Implementation options

Instead, the client should receive `GadgetDefinition` as today + `ComputedColumnsAttrs []columns.Attributes`. The server would read gadget.yaml and the BTF to compute the columns.

## Additional information

When implementing support for Wasm modules, new virtual columns could be added programmatically. I don't want the client to have to execute Wasm code. But the server could execute Wasm code to compute the `ComputedColumnsAttrs` to return to the client.

In the PoC I did in https://github.com/alban/inspektor-gadget/tree/alban_asg2023, I needed to add some special type `typedef __u8 wasm_string_t[MAX_DNS_NAME];` so that the client could notice the type `wasm_string_t` and create a new column. But I would like to create new columns from Wasm server-side without having to add special types in BTF. Therefore, this issue would be a prerequisite for implementing virtual columns from Wasm.

**Comment by alban** [comment]
I think the difficulty is that we are trying to make the json marshalling/unmarshalling work on generic types which are not known at build-time. I suggest the following alternative with the following characteristics:

* Can be marshalled & unmarshalled without knowing the underlying type
* The Go native json marshaller / unmarshaller can be used without implementing custom marshaller/unmarshaller
* Does not use the `reflect` package
* Does not produce the same json but the I think the alternative json I produce is actually useful for some client apps

```go
type ColumnValue struct {
	// Only one of the following field should be set
	I8   int8    `json:"i8,omitempty"`
	I16  int16   `json:"i16,omitempty"`
	I32  int32   `json:"i32,omitempty"`
	I64  int64   `json:"i64,omitempty"`
	U8   uint8   `json:"u8,omitempty"`
	U16  uint16  `json:"u16,omitempty"`
	U32  uint32  `json:"u32,omitempty"`
	U64  uint64  `json:"u64,omitempty"`
	F32  float32 `json:"f32,omitempty"`
	F64  float64 `json:"f64,omitempty"`
	Str  string  `json:"str,omitempty"`
	Bool bool    `json:"bool,omitempty"`
}

type Event struct {
	eventtypes.Event
	eventtypes.WithMountNsID

	Columns map[string]ColumnValue `json:"columns"`
}

type GadgetInfo struct {
	GadgetDefinition *GadgetDefinition
	ComputedColumns  []struct {
		Name string `yaml:"name"`
		Type string `yaml:"type"`
	}
}
```

An event might produce the following json:
```json
{ 
   "mountnsid" : 4026531841, 
   "timestamp" : 1697042266963594129, 
   "type" : "normal" 
   "columns" : { 
      "comm" : { 
         "str" : "bash" 
      }, 
      "gid" : { 
         "u32" : 1000 
      }, 
      "uid" : { 
         "u32" : 1000 
      } 
   }, 
}
```

An application like Headlamp might need to use `event.columns["comm"].str` instead of `event.comm` directly, but I think it is actually making things easier when writing support for arbitrary gadgets.

If an application wants to unmarshall to a native struct without the indirection (e.g. `.str` suffix), they can also easily convert the `map[string]ColumnValue` to the native struct. But it is not necessary for generic clients like kubectl-gadget, gadgetctl, Headlamp. So I don't think we should optimize for that use case.

In this way, the client would not know whether a column is coming directly from BTF, or a created from a Wasm module, or created by Inspektor Gadget by some magic types (L3Endpoint).

@flyth Wdyt?

**Comment by flyth** [comment]
I also agree that most things should happen on the server, not on the client. I'm also much in favor of sending events (mostly) in binary to reduce both bandwidth and cpu usage.

> * Can be marshalled & unmarshalled without knowing the underlying type
> * The Go native json marshaller / unmarshaller can be used without implementing custom marshaller/unmarshaller
> * Does not use the reflect package

The native JSON marshaler uses the reflect package as well. I think it's really important to not demonize reflection - both the native JSON implementation and also the columns library is optimized in a way that leverages the reflection only on initialization and not for every event/struct later on.

> * Does not produce the same json but the I think the alternative json I produce is actually useful for some client apps

This feels really odd, IMHO. I don't like both the fact that it produces "weird" looking JSON (also, what about distinguishing an empty string from a 0? - someone HAS to know what type it is) and that it requires a lot of unused memory.

### Proposal

There's a couple of things that would be great to have _in the end_:

* fully dynamic fields on initialization, meaning
  * gadgets ebpf structs can be read and transformed using btf (we already have that)
  * operators / scripts (wasm) can add fields on demand
* it should be possible to enable / disable fields (I think I mentioned this in a comparison with graphql in a previous discussion)
  * this is mainly useful to decrease network traffic, but can also be extended to ebpf with something like feature flags, so it could also reduce cpu usage
  * dynamic fields that are expensive (like IP lookups using operators / scripts) could be also handled on-demand instead of being filled out everytime
* low overhead
* low memory consumption
* low bandwidth usage

So, how to form metadata from it so that the client knows what types to expect and how to extract the values:

* from ebpf we get everything we need to know from BTF and can use a blob in conjunction with offset, size and type (the limitation of not being able to for example marshal reflect.Type can be overcome by simply reconstructing it with primitives on the client - e.g. `type: int` can then be reconstructed with reflect.TypeOf(int(0)))
* when operators / scripts register new fields, they HAVE to describe what they want to add; simple types with a fixed size can also find their way into a blob that is compact and easy to read, the only special case we need to handle are fields with dynamic lengths

A go struct definition for this could be as simple as this:

```go
type Event struct {
  Blobs [][]byte
}
```

Which is great, because we could 1:1 use a protobuf for that.

### Example

So from eBPF/BTF we could for example know that we expect a length of 8 bytes for 2 ints.
Added metadata looks like this:

```yaml
- name: int1
  size: 4
  offset: 0 # offset inside blob
  type: int
  index: 0 # target blob
- name: int2
  size: 4
  offset: 4
  type: int
  index: 0 # target blob
```

If an operator would like to add a field. it could call: `AddDynamicField("fieldname", "string")` on initialization, and in return gets a function that looks like `WriteField(entry *Entry, value []byte)`. This function would write `value` directly to `Blobs` at the index that is bound to the `AddDynamicField()` call (basically increased a counter for every dynamic field).
The metadata is extended to:

```yaml
- name: fieldname
  type: string
  index: 1
```

Now a wasm program wants to add another int, so it calls `AddInt("mycounter")` and in return gets a function back that looks like `WriteInt(entry *Entry, value int)`.
The metadata is extended to:

```yaml
- name: mycounter
  size: 4
  offset: 8
  type: int
  index: 0
```

Knowing all of this (after initialization), we would send the dynamically generated (or: augmented) metadata to the client (best case would be also protobuf serialized) who is able to process _all_ fields and easily also marshal it to JSON (using the jsonformatter). It can then initialize the colums lib properly and has all types available.
The server knows that it has to reserve 12 bytes for the first blob (used with fixed size fields) and add another blob for the dynamic string field.

While all of this might sound complex and difficult, I think it's rather normal to optimize at this point. Also, the columns library already supports a lot of this functionality. Under the hood, this is also really similar to how data is handled for e.g. protobufs.

I could go into detail on the "enabling/disabling" of fields, but that would probably go beyond the scope here. Also, we could probably blobify the dynamic fields ourselves, but in this example I relied on protobuf to handle that. Same applies to compressed primitives - e.g. protobuf uses variable int sizes to save even more bandwidth at the cost of cpu cycles.

Please let me know if anything is unclear :)

**Comment by mauriciovasquezbernal** [comment]
I pretty much agree with what you said. From a technical point of view it seems all feasible and I'd be very happy to fix the "mixed" marshaling logic that we have now (we send a json with an array of bytes in it as defined in [types.go](https://github.com/inspektor-gadget/inspektor-gadget/blob/b599f5fe8b4cb9e55e90c38b010c1dea4415729c/pkg/gadgets/run/types/types.go#L35-L46)) and move much of the columns logic to the server.

> that the client knows what types to expect and how to extract the values:

I'm wondering how the clients could consume this binary blob. I agree advance users could do it all by themselves (by using pointer arithmetic, some `unsafe` golang, etc). What about other users that don't want to get their hands dirty?

I think we should provide some helpers to:

-  get specific fields:

```golang
metadata := rpc.GetGadgetMetadata()
mycolumns := columns.FromMetadata(metadata)
pid := mycolumns.Get("pid")[int] // not sure how to specify the type on this

//....

fmt.Printf("received pid is %d\n", pid.Get(receivedEvent))

``` 

- decode the whole event into a generic type like `map[string]interface{}`:

```golang
metadata := rpc.GetGadgetMetadata()
mycolumns := columns.FromMetadata(metadata)

//....
myDecodedEvent := mycolumns.Decode(receivedEvent) // returns map[string]interface{}
fmt.Printf("received pid is %d\n", myDecodedEvent["pid"])

``` 

- decode into a golang structure  

```golang
metadata := rpc.GetGadgetMetadata()
mycolumns := columns.FromMetadata(metadata)

//
var myevent types.Event
mycolumns.Unmarshal(receivedEvent, &myevent) 
fmt.Printf("received pid is %d\n", myevent.Pid)
``` 

`types.Event` can be provided by the user itself (tagging fields  with `columns`) or provided by the gadget. Actually it's interesting because we could generate that structure at build time with `ig image build` (as [bpf2go](https://pkg.go.dev/github.com/cilium/ebpf/cmd/bpf2go) does). 

> There's a couple of things that would be great to have in the end:

IMO it's missing
- easy way to handle data on client 

I think the idea you proposed makes sense for kubectl-gadget / gadgectl, or any other **golang** application that consumes data from a gadget, both, by using our gRPC interface or by running the gadgets directly with https://github.com/inspektor-gadget/inspektor-gadget/issues/2021. However we're still missing a use case: applications written in other languages that don't have access to the columns library. For that case the server should send json to the client, and probably another version of the metadata file with information about that json structure, like descriptions, types, annotations, etc. 

wdyt?

**Comment by flyth** [comment]
Totally agree with the helper functions for third parties - and great idea to have an option to create the go structs (although we'd need to take care of the dynamically added parts somehow)! 

At a later stage we could probably also try to make our wire protocol compatible with protobufs directly and have `build` generate a .proto file - that would greatly improve compatibility with other languages / consumers as well. However, this would have the same issue with the dynamic fields. I'll gladly look into optimizing such things once we have a stable version ready.

Regarding other third party clients: we _have_ to offer a direct endpoint at the server side that is able to render data to other formats like JSON - Headlamp for example will use that. If you want to use IG from another language, you should use such server side rendering like you also said. The downside is just a bit increased CPU and bandwidth usage.

**Comment by flyth** [comment]
Here's a [quick PoC](https://github.com/inspektor-gadget/inspektor-gadget/commit/1d18b3982cb2d6586bbc9d93a0be72473dd9c302) of what I proposed. We actually have most of what we need in place already, just needs a bit of cleanup and _much_ more error handling in case we do all of that based on user data. For JSON, the string marshaling is missing right now.

Output of that example is:
```
[[1 0 0 0 2 0 0 0 255 255 0 0 0 0 0 0] [79 112 101 114 97 116 111 114 32 115 97 121 115 32 104 105 33]]
Demo: 1
Foo: 2
Operator: [79 112 101 114 97 116 111 114 32 115 97 121 115 32 104 105 33]
WASM: 65535
JSON: {"Demo": 1, "Foo": 2, "wasmnum": 65535}
```

**Comment by alban** [comment]
I am confused about the PoC and the new code defining marshalling with managing offsets etc.

I initially filed this issue because it is blocking me for the wasm implementation. But it seems we're discussing a new rpc system that would support both json and something custom. It seems it will take some time to implement.

Should I implement the Wasm execution as it was done in the asg2023 branch with the type `wasm_string_t` in BTF first, and refactor it later when this GadgetInfo() issue is resolved?

**Comment by mauriciovasquezbernal** [comment]
I did some experimentation of the ideas above in https://github.com/inspektor-gadget/inspektor-gadget/commits/mauricio/experiments/create-columns-server-side. 

This POC:
- Avoids the client having to parse BTF. It uses a new type definition that can be easily converted to `columns.DynamicField`
- Allows the server to create new "virtual" columns,   they can come from wasm or other sources

The code is very hacky and based on main, however it won't be too difficult to rebase it on top of https://github.com/inspektor-gadget/inspektor-gadget/pull/2107 if needed. 

Things to discuss:
- I didn't used the columns library on the "server part" to fill the blob. I think that library is useful but IMO we need to split / rename it
- I felt I was reinventing the wheel when defining `type Type struct`, it's like a very limited version of BTF. Perhaps having the client to decode the BTF information is not too bad after all and we can use it to describe the columns we add to the event?

**Comment by alban** [comment]
I like this PoC. I'll try to use it. I think it is best to avoid decoding BTF from the client side. Some types don't exist in BTF, such as strings.

I added a couple of comments on your commits: I think the endienness has to be fixed to support clients/servers of different endienness.

**Comment by flyth** [comment]
I also think the direction is good, thanks for trying it out directly!

> * I didn't used the columns library on the "server part" to fill the blob. I think that library is useful but IMO we need to split / rename it

As long as it's not trying to do the same, I think that's fine. But we need to add proper testing of lengths / types and IMHO it's best to avoid managing that in two places.

> * I felt I was reinventing the wheel when defining type Type struct, it's like a very limited version of BTF. Perhaps having the client to decode the BTF information is not too bad after all and we can use it to describe the columns we add to the event?

I think it's just the usual overhead of serialization - and that it's better to abstract it a bit and leave BTF out of the picture. If you'd implement a library that handles our metadata in another language, you'd at least not have to also handle/maintain BTF.
