### ISSUE TITLE
[RFE] artifacthub: Add Gadget kind

### ISSUE THREAD

**Issue by mqasimsarfraz** [inspektor-gadget/inspektor-gadget#2175]
## Current situation

Currently all the gadgets are published as [packages](https://github.com/orgs/inspektor-gadget/packages?repo_name=inspektor-gadget) in container registry. In order to improve the discovery of the gadgets, we can publish them as a kind in [artifacthub](https://artifacthub.io/packages/search). We can also use the "Official" and "CNCF" badges to mark the gadgets maintained by us. 

## Impact

Improves the discovery of gadgets

## Implementation options

The [comment](https://github.com/artifacthub/hub/issues/2271#issuecomment-1235378557) gives an idea about the implementation, we need check if we need a [special tracker](https://github.com/artifacthub/hub/tree/master/internal/tracker/source) or a generic tracker can do a trick for us. A good starting point is opening an [issue](https://github.com/artifacthub/hub) to start conversion.  Some exmaples:

- https://github.com/artifacthub/hub/issues/2271
- https://github.com/artifacthub/hub/pull/2902
- https://github.com/artifacthub/hub/pull/514

**Comment by alban** [comment]
Thanks for filing this issue. I agree it would be good to have a gadget kind.

---

Meanwhile, since artifacthub does not have a gadget kind yet, I was experimenting on [runc-vuln-gadget](https://github.com/alban/runc-vuln-gadget/) with the [container image kind](https://artifacthub.io/docs/topics/repositories/container-images/).

Steps:
* Ensure the gadget is public on the OCI registry (on GitHub, click on "Package settings")
* Ensure the OCI image index has the correct annotations on the **latest** tag. Example of Makefile target:
```Makefile
add-annotations:
        export VCS_DATE="$(shell date -d "@$(shell git log -1 --format=%at)" +%Y-%m-%dT%H:%M:%SZ --utc)" ; \
        export VCS_SOURCE="https://github.com/alban/runc-vuln-gadget/" ; \
        export VCS_SHA="$(shell git rev-list -1 HEAD)" ; \
        regctl image mod \
                $(CONTAINER_REPO):latest \
                --replace \
                --to-oci-referrers \
                --time-max "$${VCS_DATE}" \
                --annotation "org.opencontainers.image.description=A gadget to detect runc vulnerabilities" \
                --annotation "org.opencontainers.image.created=$${VCS_DATE}" \
                --annotation "oci.opencontainers.image.source=$${VCS_SOURCE}" \
                --annotation "org.opencontainers.image.url=$${VCS_SOURCE}" \
                --annotation "oci.opencontainers.image.revision=$${VCS_SHA}" \
                --annotation "org.opencontainers.image.documentation=https://github.com/alban/runc-vuln-gadget/" \
                --annotation "io.artifacthub.package.readme-url=https://raw.githubusercontent.com/alban/runc-vuln-gadget/56de6e1e25353dff490429d45b04b2fc0ab61a8f/README.md"
        regctl image manifest \
                $(CONTAINER_REPO):latest
```

* Login on https://artifacthub.io/ with GitHub credentials
* Register the gadget
  * Kind: Container images
  * URL: oci://ghcr.io/alban/runc-vuln-gadget
  * Once registered, note the repositoryID
* Create artifacthub-repo.yml: with the repositoryID from above.
```yaml
repositoryID: CHANGEME
owners:
  - name: CHANGEME
    email: CHANGEME
```
* Push it in the special `artifacthub.io` tag:
```Makefile
push-artifacthub:
        oras push \
                $(CONTAINER_REPO):artifacthub.io \
                --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
                artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
```

But I didn't get it to work yet...

**Comment by alban** [comment]
Adding annotations in `ig image build`: https://github.com/inspektor-gadget/inspektor-gadget/pull/2522

**Comment by alban** [comment]
https://github.com/artifacthub/hub/issues/3665

**Comment by mauriciovasquezbernal** [comment]
@alban are we missing anything to close this one?

**Comment by alban** [comment]
> @alban are we missing anything to close this one?

I think it can be closed.

I still want to have #2586 but it's more a helper than strictly necessary.
