### ISSUE TITLE
[Potentional Bug] NRI hook doesn't work when other NRI plugins were loaded before IG

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#2343]
## This is only from a static analysis by me

If I understand the line https://github.com/inspektor-gadget/inspektor-gadget/blob/63e8451a8f950381782428264a478fc9fdfe4a3d/gadget-container/entrypoint/entrypoint.go#L174 correctly we only add the `Type` to the existing config. In our config we also specify the `"conf":{"socketFile": "..."}` and this is not done for this case.

If there was no existing nri config we just copy our correct config, therefore it works.

This issue was already in the code before the refactoring `entrypoint` to a `.go` file: https://github.com/inspektor-gadget/inspektor-gadget/blob/387a66b877ffdca57739db0550d076cc38fc016c/gadget-container/entrypoint.sh#L97

Is my assumption correct? (If yes I will fix it in https://github.com/inspektor-gadget/inspektor-gadget/pull/2208)

cc @alban as codeowner

**Comment by alban** [comment]
It looks like a bug, yes.

Instead of keeping the two files in sync:
- gadget-container/hooks/nri/conf.json
- gadget-container/entrypoint/entrypoint.go

I suggest that the Golang code does not hard code `&nriv1.Plugin{Type: "nrigadget"}` but instead takes the content of `conf.json` with a `go:embed`.

Additionally:
- It should check that `configList.Version` is "0.1" and refuses to overwrite the file if not.
- It should check if nrigadget with the same configuration is already there, and don't add it twice in the list.

I guess you're checking this because of #2208... I suggest to add a setting for the namespace in addition to the `socketFile` setting, so the several NRI gadget plugins could be distinguished from each other.

Similarly, [removeNRIHooks](https://github.com/inspektor-gadget/inspektor-gadget/blob/63e8451a8f950381782428264a478fc9fdfe4a3d/gadget-container/cleanup/cleanup.go#L62) needs to be adapted.

**Comment by burak-ok** [comment]
The referenced PR is still open but on hold
