### ISSUE TITLE
[RFE] Allow more flexible filtering for the seccomp policy advisor

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#265]
## Current situation

When creating a trace for the seccomp policy advisor, the user needs to specify the node name, the namespace and the podname that are going to be traced. This diverges from most of our gadgets where we allow a lot more flexibility for the filtering

## Impact

It's not possible to trace deployments that use generated names until the pod is already created. And in that case only one pod can be traced. Also, one needs to know in which node the pod will be running.

## Ideal future situation

Ideally we should allow the same kind of flexibility that we see on other gadgets that allow the user to filter by label, or just trace the whole namespace. 

It might be that this was a design decision related to the use of CRDs, but I think we need to find a solution that allows us to provide the same flexibility the other gadgets provide.

**Comment by alban** [comment]
It's possible to get seccomp profile for pods using generated names but I agree the UX needs to be improved. Steps:
1. Create a first Trace CR without filter and start it. The seccomp gadget always monitors all containers and the BPF map contains syscalls data for all containers regardless of TraceSpec.Filter.
2. Create a second Trace CR with the filter set to the chosen pod. Even if the second Trace CR was started after the pod to trace, it will be able to generate the seccomp profile because the seccomp tracer is a singleton so it was started when the first Trace CR was started. The TraceSpec.Filter field is only read during the "generate" operation.

Alternatively, users could create a single Trace CR and they could update the filter between the "start" and the "generate" operations. (but the UX is also not good)

Another problem is that the current implementation does not allow to select a pod that has terminated. This makes it impossible to get a seccomp profile for a short-lived pod.

**Comment by marga-kinvolk** [comment]
I see, this is good to know and I was not aware that the Filter was only read during the generation.

Is there a reason why the filter needs to be done by exact podname, instead of how it's done for the other gadgets?

I also run into the pod terminated issue. Should I file a separate bug about that, or is that related to the filtering?

**Comment by alban** [comment]
> Is there a reason why the filter needs to be done by exact podname, instead of how it's done for the other gadgets?

It is now possible to do, now that Jose implemented GetContainersBySelector(). I think we should implement it, in case the user wants to select a pod by labels.

Not all use cases make sense though because it could generate a single Seccomp Policy for several pods that might not be related (with `OutputMode=ExternalResource`, the `Output` field can only specify one Seccomp Policy resource name).

And also if the user wants to select several pods, those pods might not be scheduled on the same node; in that case, the seccomp gadget is not able to merge the Seccomp Policy across nodes because we don't have a GlobalTrace CRD yet (same issue with the Network Policy Advisor).

**Comment by blanquicet** [comment]
As discussed in [#367](https://github.com/kinvolk/inspektor-gadget/issues/367), before implementing this task, the following  tasks need to have been already implemented:

- [ ] #377 
- [ ] #206

**Comment by bbigras** [comment]
I would like to be able to catch a pod as soon as it starts. Maybe with a label instead of the pod name.

My use case is that I don't want to miss any syscall that my app might do only at startup.
