### ISSUE TITLE
Version skew in CI

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#2905]
The CI reports a version skew between client and server:
> time="2024-05-28T16:36:16Z" level=warning msg="version skew detected: client (v5287634.0.0) vs server (v0.0.0)"
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/9272883910/attempts/1#summary-25512185393

I guess we are doing something wrong when compiling the image and the CLI in the CI?

**Comment by mqasimsarfraz** [comment]
> I guess we are doing something wrong when compiling the image and the CLI in the CI?

I wonder if this is about failed parsing of the [version here](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/cmd/common/utils/version-checker.go#L34). The CI runs other than releases won't be semver. Right?

**Comment by mauriciovasquezbernal** [comment]
I think the issue is that specific commit (https://github.com/inspektor-gadget/inspektor-gadget/commit/5287634) pass the [semver parsing validation](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/cmd/common/utils/version-checker.go#L34) 

```bash 
$ cd /tmp
$ mkdir foo
$ cd foo/
$ git init .
$ git config --local gc.auto 0
$ git remote add origin https://github.com/inspektor-gadget/inspektor-gadget
$ git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin 5287634c19199fe60fff58a07f5b4d937d9e5739:refs/remotes/origin/main
$ git sparse-checkout disable
$ git checkout --progress --force -B main refs/remotes/origin/main
$  make kubectl-gadget
$ git describe --tags --always
5287634
$ ./kubectl-gadget version
INFO[0000] Experimental features enabled
Client version: v5287634.0.0
```

I'm wondering if we should set `fetch-tags` on the checkout action or even [`fetch-depth: 0`](https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches)
