### ISSUE TITLE
[trace exec] fanotify: too many open files / 

### ISSUE THREAD

**Issue by galofir-ms** [inspektor-gadget/inspektor-gadget#2967]
## Description

After running a process executing IG for more than a few hours, fanotify errors start to appear.

We've seen evidence of multiple errors:

![image](https://github.com/inspektor-gadget/inspektor-gadget/assets/146319678/76e16c03-3bab-4c70-9ab0-4dab4e76e66f)

## Impact
K8s enrichment stops working

@alban

**Comment by alban** [comment]
I can reproduce this bug by running the following on the host:

```bash
mkdir -p  /tmp/test-runc/userdata
touch /tmp/test-runc/userdata/config.json
for i in `seq 128` ; do
    echo -n .
    runc create --bundle /tmp/test-runc --pid-file /tmp/test-runc/mypid &> /dev/null
done
echo
```

Then, ig outputs:
```
ERRO[0345] error monitoring runtime instance: fanotify: init error, too many open files 
```


I think `container-hook/tracer.go`/`parseOCIRuntime()` should have the following improvements:
- [ ] `n.monitorRuntimeInstance` should have a timeout: if runc didn't create the pid file in 2 seconds, don't monitor the directory forever. Or at least, when the runc process terminates without creating the pid file, cancel the monitoring.
- [ ] Check that the pid file is created by the correct pid of runc
- [ ] Different call instances of `parseOCIRuntime` could reuse the same fanotify group to avoid the limit [FANOTIFY_DEFAULT_MAX_GROUPS=128](https://github.com/torvalds/linux/blob/v6.6/fs/notify/fanotify/fanotify_user.c#L32)
- [ ] Ignore invalid `runc` commands (the call to `runc create` in my test script is not valid syntax since it does not have a container-id)

**Comment by alban** [comment]
Instead of running  `runc create` manually, I can also trigger the bug by attempting to start a container with a bad configuration:
```
$ docker run --rm -it --name busybox -v /dev/null/null:/tmp/null busybox
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/dev/null/null" to rootfs at "/tmp/null": stat /dev/null/null: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

In this case, docker/containerd executes:
- `runc create`: it will cause `runc:[2:INIT]` to terminate with exit code 1 according to bcc's exitsnoop (without writing the pidfile and without exec'ing the container entrypoint) 
- `runc delete`

Then, ig waits forever for this pid file.

This could be a scenario in Kubernetes: a pod failing to start because it uses an invalid `volumeMounts` in the pod spec.

**Comment by alban** [comment]
I implemented the reproducer as a test: https://github.com/inspektor-gadget/inspektor-gadget/pull/2998
