### ISSUE TITLE
Path enrichment in gadgets

### ISSUE THREAD

**Issue by amitschendel** [inspektor-gadget/inspektor-gadget#3117]
## Current situation

The current situation is that in some gadgets (e.g exec) we get the path to the file of the process but in most gadgets we don't.

## Impact

We need the path for many use cases in our system and in general I think it's a nice enrichment to show/have.

## Ideal future situation

Adding this code in the gadget will give the path to the file. 
```c
struct file *exe_file = BPF_CORE_READ(current_task, mm, exe_file);
char *exepath;
exepath = get_path_str(&exe_file->f_path);
bpf_probe_read_kernel_str(event->exepath, MAX_STRING_SIZE, exepath);
```
An example can be taken from [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/755c7bab660a6bcedc562f0609248390394c3639/pkg/gadgets/trace/exec/tracer/bpf/execsnoop.bpf.c#L214)

Something to note is that it can have performance impact so we might want to add a flag in the config before enabling it by default, the same way it exists today in the exec gadget.

## Additional information

[Slack discussion](https://kubernetes.slack.com/archives/CSYL75LF6/p1720008042474399)

CC: @alban

**Comment by amitschendel** [comment]
For me I would love to have it in the following gadgets:
dns,network,open,seccomp

**Comment by alban** [comment]
Thanks for filing this issue. For me, I'd like to have it in the following gadgets: trace-exec (already there) and dns (#2684).

For the networking gadgets (dns, sni, network), it's going to be implemented in the socket enricher because we don't have `current_task` in that context.

**Comment by alban** [comment]
```c
struct file *exe_file = BPF_CORE_READ(current_task, mm, exe_file);
char *exepath;
exepath = get_path_str(&exe_file->f_path);
bpf_probe_read_kernel_str(event->exepath, MAX_STRING_SIZE, exepath);
```
It is not always safe to pick up `current->mm->exe_file`. Consider a multi-threaded process where one thread is calling 
[prctl(PR_SET_MM, PR_SET_MM_EXE_FILE, ...)](https://www.man7.org/linux/man-pages/man2/PR_SET_MM_EXE_FILE.2const.html) to replace `exe_file`. This could have two problems:
- If security policies depends on `exe_file`, this could be problematic since unprivileged processes can change their `exe_file`. (it might not matter if the gadget is not used with this goal)
- If a multi-threaded process changes `exe_file` in one thread while it is being read in the ebpf program by another thread, this could lead to reading a bad memory address and undefined behaviour.

Reading `exe_file` in the context of `execve` does not have this problem because it is locked. But extending `exepath` to other gadgets than trace-exec needs careful consideration.

One way to solve this would be to cache the exepath at execve-time in a hash map, so it could be read later outside of the context of execve.

Related discussions: https://lore.kernel.org/bpf/CAADnVQ+noVorD70rmtESE3MkDHnkQgraNNBCadJ=0x6-nBwhvA@mail.gmail.com/T/

**Comment by amitschendel** [comment]
> ```c
> struct file *exe_file = BPF_CORE_READ(current_task, mm, exe_file);
> char *exepath;
> exepath = get_path_str(&exe_file->f_path);
> bpf_probe_read_kernel_str(event->exepath, MAX_STRING_SIZE, exepath);
> ```
> 
> It is not always safe to pick up `current->mm->exe_file`. Consider a multi-threaded process where one thread is calling [prctl(PR_SET_MM, PR_SET_MM_EXE_FILE, ...)](https://www.man7.org/linux/man-pages/man2/PR_SET_MM_EXE_FILE.2const.html) to replace `exe_file`. This could have two problems:
> 
> * If security policies depends on `exe_file`, this could be problematic since unprivileged processes can change their `exe_file`. (it might not matter if the gadget is not used with this goal)
> * If a multi-threaded process changes `exe_file` in one thread while it is being read in the ebpf program by another thread, this could lead to reading a bad memory address and undefined behaviour.
> 
> Reading `exe_file` in the context of `execve` does not have this problem because it is locked. But extending `exepath` to other gadgets than trace-exec needs careful consideration.
> 
> One way to solve this would be to cache the exepath at execve-time in a hash map, so it could be read later outside of the context of execve.
> 
> Related discussions: https://lore.kernel.org/bpf/CAADnVQ+noVorD70rmtESE3MkDHnkQgraNNBCadJ=0x6-nBwhvA@mail.gmail.com/T/

That's a good point! Thanks for pointing this out.
Maybe we can resolve that hard link in some way as an alternative to holding a cache? because we would need to implement a way to track when processes dies and remove them from the cache as well.
@alban
