### ISSUE TITLE
trace_tcpdrop failed: map spec is incompatible with existing map

### ISSUE THREAD

**Issue by cr7258** [inspektor-gadget/inspektor-gadget#3477]
## Description
https://www.inspektor-gadget.io/docs/latest/gadgets/trace_tcpdrop
```
kubectl gadget run ghcr.io/inspektor-gadget/gadget/trace_tcpdrop:latest
K8S.NODE             K8S.NAMESPACE        K8S.PODNAME         K8S.CONTAINERNAME   SRC                       DST                       MOUNT_NS_… COMM              PID        TID STATE      TCPFLAGS   REASON
Error: rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: using replacement map gadget_sockets: ValueSize: 64 changed to 8272: map spec is incompatible with existing map
rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: using replacement map gadget_sockets: ValueSize: 64 changed to 8272: map spec is incompatible with existing map
rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: using replacement map gadget_sockets: ValueSize: 64 changed to 8272: map spec is incompatible with existing map
rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: using replacement map gadget_sockets: ValueSize: 64 changed to 8272: map spec is incompatible with existing map
rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: using replacement map gadget_sockets: ValueSize: 64 changed to 8272: map spec is incompatible with existing map
rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: using replacement map gadget_sockets: ValueSize: 64 changed to 8272: map spec is incompatible with existing map
```

## Environment and steps to reproduce

```bash
kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.12

kubectl gadget version
Client version: v0.32.0
Server version: v0.32.0
```

**Comment by alban** [comment]
Hi,
This is due to #2684 changing the [gadget eBPF API](https://inspektor-gadget.io/docs/latest/gadget-devel/gadget-ebpf-api#socket-enrichment) between the gadget and the socket enricher.
For now, we don't provide compatibility (see [Support Inspektor Gadget API changes](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md#support-inspektor-gadget-api-changes)). See also https://github.com/inspektor-gadget/inspektor-gadget/pull/2683#issuecomment-2173698130.

You use Inspektor Gadget v0.32.0 (before #2684) and gadget `trace_tcpdrop:latest` (after #2684). Could you try [`trace_tcpdrop:v0.32.0`](https://github.com/inspektor-gadget/inspektor-gadget/pkgs/container/gadget%2Ftrace_tcpdrop/266843729?tag=v0.32.0)?
```
kubectl gadget run ghcr.io/inspektor-gadget/gadget/trace_tcpdrop:v0.32.0
```

I think we should improve the error message: even if we don't support compatibility yet, we can tell users how to solve the problem.

**Comment by alban** [comment]
I added a warning message in #3479.

**Comment by mauriciovasquezbernal** [comment]
> We suggest the image trace_tcpdrop:latest (and not trace_tcpdrop:v0.32.0). Should we change that?

Absolutely. We should suggest to use the specific tag for the gadget images (and also for the gadget container when ig on a container). I see some projects have a special tag in the documentation with the version (see https://github.com/cilium/tetragon/blob/663dfdbd2fffd3564b843cf3fd53600b07774fd9/docs/content/en/docs/getting-started/install-docker.md?plain=1#L29), but I don't know if Docusaurus supports something like it.

**Comment by cr7258** [comment]
> Could you try [trace_tcpdrop:v0.32.0](https://github.com/inspektor-gadget/inspektor-gadget/pkgs/container/gadget%2Ftrace_tcpdrop/266843729?tag=v0.32.0)?
kubectl gadget run ghcr.io/inspektor-gadget/gadget/trace_tcpdrop:v0.32.0

Thanks @alban, it works.
