### ISSUE TITLE
Exepath field of trace exec (both built-in and image-based) gadget may be empty

### ISSUE THREAD

**Issue by Sefi4** [inspektor-gadget/inspektor-gadget#3767]
## Description

There are circumstances where exepath may be empty. One scenario (suggested by @alban) is where a file without a Shebang is being executed, thus `execve` isn't triggered and exepath populated with an empty string. I thought it may be possible to make sure exepath is always populated, by using args[0] only in the case where exepath is empty. To overcome the possibility of args[0] being relative, I thought to use `absPath := filepath.Clean(filepath.Join(cwd, args[0]))`. And to solve args[0] being symlink I though using `secureExe, err := securejoin.SecureJoin("/proc/<containerPid>/root/", absPath)` where containerPid is the pid of the container (which was added recently). Then, exepath is being populated from secureExe (after trimming the container root fs path).

Do you guys think this logic is valid? If so, do you think it's something worth merging to the trace exec gadgets (both image and built-in) or exepath should be exactly `task->mm->exe_file->f_path`?

**Comment by alban** [comment]
For more context:
```
$ echo 'cat /etc/hostname' > script.sh
$ chmod +x script.sh
$ strace -f -e execve,openat sh -c ./script.sh
execve("/usr/bin/sh", ["sh", "-c", "./script.sh"], 0x7fff8b5e4698 /* 76 vars */) = 0
...
execve("./script.sh", ["./script.sh"], 0x562082406800 /* 76 vars */) = -1 ENOEXEC (Exec format error)
openat(AT_FDCWD, "./script.sh", O_RDONLY) = 3
...
[pid 94206] execve("/usr/bin/cat", ["cat", "/etc/hostname"], 0x562082406800 /* 76 vars */) = 0
```

Notice that `execve` returns `ENOEXEC` because the script does not have a shebang. Then, the shell fallbacks on opening the script with `openat` and interpret it without `execve`.

The failed execve is captured by Inspektor Gadget with ret=-8:

```
$ sudo ig trace exec --host --paths -o columns=comm,pcomm,ret,args,exepath
COMM             PCOMM            RET ARGS                                     EXEPATH
strace           bash             0   /usr/bin/strace -f -e execve,openat sh … /usr/bin/strace
sh               strace           0   /usr/bin/sh -c ./script.sh               /usr/bin/bash
sh               strace           -8  ./script.sh
cat              sh               0   /usr/bin/cat /etc/hostname               /usr/bin/cat
```

This issue is about adding the exepath when execve fails.

In the ebpf source `pkg/gadgets/trace/exec/tracer/bpf/execsnoop.bpf.c`, `bpf_perf_event_output` is called from two different places:
- `tracepoint/sched/sched_process_exec` when the execve succeeds
- `tracepoint/syscalls/sys_exit_execve` when the execve fails

`event->exepath` should be prepared in the `tracepoint/syscalls/sys_exit_execve` case too.

We cannot use `/proc/<containerPid>/root/` because it would be asynchronous and the process might have terminated by then.

**Comment by Sefi4** [comment]
> `event->exepath` should be prepared in the `tracepoint/syscalls/sys_exit_execve` case too.

Sounds much better. I'll start working on it

**Comment by Sefi4** [comment]
> Then, the shell fallbacks on opening the script with openat and interpret it without execve

In that case, is it make sense to populate `exepath` with the path to the shell that interprets the script? Thus, we'll have a consistency when running a script with and without the Shabeng
