### ISSUE TITLE
Uniform trace custom resource and command line parameters

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#598]
Some gadgets like filetop define the names of the parameters and export them in the type package: https://github.com/kinvolk/inspektor-gadget/blob/29cf47f873680ad404fe14330ca3815f498b234c/pkg/gadgets/filetop/types/types.go#L32-L37

and these are used when defining the `parameters` field of the trace CR

https://github.com/kinvolk/inspektor-gadget/blob/29cf47f873680ad404fe14330ca3815f498b234c/cmd/kubectl-gadget/filetop.go#L72-L77

The problem is that the name of the parameter is not used in the CLI arguments 

https://github.com/kinvolk/inspektor-gadget/blob/29cf47f873680ad404fe14330ca3815f498b234c/cmd/kubectl-gadget/filetop.go#L103-L105

and the description is also duplicated as well in the trace documentation

https://github.com/kinvolk/inspektor-gadget/blob/29cf47f873680ad404fe14330ca3815f498b234c/pkg/gadgets/filetop/gadget.go#L60-L64

There are some gadgets that don't export the parameters and they are hardcoded around, for instance:

https://github.com/kinvolk/inspektor-gadget/blob/29cf47f873680ad404fe14330ca3815f498b234c/pkg/gadgets/bindsnoop/gadget.go#L111-L145

https://github.com/kinvolk/inspektor-gadget/blob/29cf47f873680ad404fe14330ca3815f498b234c/cmd/kubectl-gadget/bindsnoop.go#L61-L65

And ideal situation would be:
- All gadgets expose the names of the parameters (and their descriptions) in the types package
- The names of those are reused in the trace and CLI implementations

**Comment by marga-kinvolk** [comment]
I spent quite some time thinking about this and trying to find an elegant way to solve this issue. What I wanted to do was use something like the flags package, but for the gadget parameters, so that the exposed names could come programatically from the same place, the documentation could be automatically generated in an uniform way, etc. The problem that I ran into is that there doesn't seem to exist a package that does this. Making this work would mean making a derivative of the flag package that adapts it to work as needed. I started to do this work, but other things took priority and I couldn't finish it :(.

I was aiming for something along these lines. In each gadget a function that specifies the parameters, with their default values and descriptions:

```
func (f *TraceFactory) Parameters() {
    f.Desc = "filetop shows reads and writes by file, with container details"
    f.Params = flag.NewFlagSet("parameters", flag.ExitOnError)
    f.Params.IntVar(&max_rows, "max_rows", 20, "Maximum rows to print")
    f.Params.IntVar(&interval, "interval", 1, "Output interval, in seconds")
    f.Params.StringVar(&sort_by, "sort_by", "ALL", "The field to sort the results by")
    f.Params.BoolVar(&all_files, "all_files", false, "Show all files")
}
```

In the base class, a Description() function that uses the parameters above to create the documentation:

```
func (f *BaseFactory) Description() string {
    f.Parameters()
    params := "The following parameters are supported:\n"
    f.Params.VisitAll(func(p *flag.Flag) {
        format := " - %s: %s. (default %s)\n"
        params += fmt.Sprintf(format, p.Name, p.Usage, p.DefValue)
    })
    return fmt.Sprintf("%s.\n%s", f.Desc, params)
}
```

That's as far as I got in terms of writing the code. This is missing exposing the parameters to the gadgets and setting the values when the gadget gets invoked.

**Comment by mauriciovasquezbernal** [comment]
A solution similar to what @margamanterola proposed above was implemented in https://github.com/inspektor-gadget/inspektor-gadget/pull/1281
