### ISSUE TITLE
Custom columns are not always discoverable

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#856]
## Description

The documentation [general-usage.md](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/guides/general-usage.md#custom-columns) says:
> Using `-o custom-columns=column1,column2` we can choose which columns to print. We can use the JSON output to know the names of all the available columns for a given gadget.

However, it is not always true:

```
$ ./kubectl-gadget top ebpf -o json
{"node":"aks-agentpool-37135575-vmss000000","progid":168,"pids":[{"pid":1,"comm":"systemd"}],"type":"CGroupSKB"}
{"node":"aks-agentpool-37135575-vmss000000","progid":169,"pids":[{"pid":1,"comm":"systemd"}],"type":"CGroupSKB"}
{"node":"aks-agentpool-37135575-vmss000000","progid":170,"pids":[{"pid":1,"comm":"systemd"}],"type":"CGroupSKB"}
{"node":"aks-agentpool-37135575-vmss000000","progid":171,"pids":[{"pid":1,"comm":"systemd"}],"type":"CGroupSKB"}
{"node":"aks-agentpool-37135575-vmss000000","progid":172,"pids":[{"pid":1,"comm":"systemd"}],"type":"CGroupSKB"}
{"node":"aks-agentpool-37135575-vmss000000","progid":173,"pids":[{"pid":1,"comm":"systemd"}],"type":"CGroupSKB"}
```

* The output shows `pids` but it cannot be used as a column.
* Because of `omitempty` tags, we don't see the columns `name`, `runtime`, etc.

## Impact

Custom columns not discoverable from the command line.

## Environment and steps to reproduce

1. **Set-up**:
2. **Task**:
3. **Action(s)**: `./kubectl-gadget top ebpf -o json`
4. **Error**: not all columns discoverable

## Expected behavior

There should be a command to find the list of columns. None of the following commands help:

```
$ ./kubectl-gadget top ebpf -o help
$ ./kubectl-gadget top ebpf -h
```

**Comment by mauriciovasquezbernal** [comment]
The name of the available columns is now printed in the help message after https://github.com/inspektor-gadget/inspektor-gadget/pull/1281:

```
$ sudo ./local-gadget top ebpf -h
Periodically report ebpf runtime stats

...
  -o, --output string     Output format (json, columns).
                          
                          Columns (columns)
                            The output of the gadget is formatted in human readable columns.
                            You can optionally specify the columns to output using '-o columns=col1,col2,col3' etc.
                              Available columns:
                                comm
                                container
                                cumulruncount
                                cumulruntime
                                mapcount
                                mapmemory
                                name
                                pid
                                progid
                                runcount
                                runtime
                                totalRunCount
                                totalruntime
                                type
...
```

Regarding `pid` vs `pids`, we're using different names for the column and the json field https://github.com/inspektor-gadget/inspektor-gadget/issues/1146, it seems to me this restriction can only be lifted and we can print multiple PIDS?

What do you think @flyth?

**Comment by flyth** [comment]
Yeah, having multiple entries in one column is tricky, especially for output on the console: for the pids, we _could_ add additional rows (where only the PID field would appear), but that doesn't scale if we would have two columns with multiple entries - so I don't think that's a good way.

After #1281 we now have an `ExtraLines()` interface to add additional "describing" lines to the output that could be used for some things. This whole thing gets also especially interesting when we export to third parties (like a web interface), where we may want to have the array rather than what the Extractor() returns.

But I think this issue here is solved (well, after the second PR also updating kubectl-gadget), as we now have the help text showing the columns - afaiu @alban was just using the JSON output to find out which columns there were and that didn't help. Still, the [docs](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/gadgets/common-features.md) should be updated (after the second PR) to reflect that you don't need to look at the JSON output anymore.

**Comment by mauriciovasquezbernal** [comment]
I'll close this issue an open a PR with an idea to fix the pids vs pid thing.
