### ISSUE TITLE
Consider renaming `NewTracer` function on gadget tracers

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#905]
## Current situation

Currently, [the packages](https://github.com/kinvolk/inspektor-gadget/tree/main/pkg/gadgets) we are exposing to be able to run the gadget tracers directly provides the following API:

- `func NewTracer(*Config, gadgets.DataEnricher, func(types.Event)) (*Tracer, error)`: Creates and run the tracer. Example in [trace/bind](https://github.com/kinvolk/inspektor-gadget/blob/256eb8fd9c3142151d84b020b98d5f43648dd6e1/pkg/gadgets/trace/bind/tracer/tracer.go#L84), [top/tcp](https://github.com/kinvolk/inspektor-gadget/blob/256eb8fd9c3142151d84b020b98d5f43648dd6e1/pkg/gadgets/top/tcp/tracer/tracer.go#L86).
- `func (t *Tracer) Stop()`: Stops the tracer.

## Impact

It creates some confusion as `NewTracer` is actually creating and running the trace, while its name only describes the creation. It creates some confusion for the caller. See [this discussion](https://github.com/kinvolk/inspektor-gadget/pull/896#discussion_r961562416).

## Ideal future situation

Naming should be more accurate with what the function is actually doing. 

## Additional information

Take into account that changing this naming will also imply changing the gadget examples, thus updating the blog-post that describes them.

**Comment by mauriciovasquezbernal** [comment]
After https://github.com/inspektor-gadget/inspektor-gadget/pull/1281 these functions aren't used anymore, we're keeping them in order to avoid breaking users that use our gadgets directly from their golang code. Also, we're leaning towards supporting [containerized gadgets](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md) as the default way to run gadgets, so this code will be moved to legacy later on. 

I don't think it makes sense to expend time renaming those functions if they are going to be deprecated.
