### ISSUE TITLE
top/ebpf: Map size calculation is not accurate 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#924]
Current implementation computes the size of the map manually by using the key size, value size and number of entries. 

https://github.com/kinvolk/inspektor-gadget/blob/ad87c3f5407ae5bd30d9fc486e79df4662ec19ae/pkg/gadgets/top/ebpf/tracer/tracer.go#L208

This calculation is not totally correct as the allocated map memory on the kernel is different. For instance, key sizes are rounded up to 8 bytes, so this calculation gives a misleading result when the key size is not a multiple of 8.

bpftool gets this information using procfs -> https://github.com/libbpf/bpftool/blob/3e8e34bcc34287dc2eba6abec8313b8cc980dfa6/src/map.c#L466, think we can follow the same approach here.

/cc @alban @flyth

**Comment by alban** [comment]
That's great, I didn't know that fdinfo was giving this. It was introduced in Linux 4.10 via https://github.com/torvalds/linux/commit/21116b7068b9b66ac16b2fe3675469f459968c3f. The top-ebpf gadget requires Linux 5.1 so that's fine.

The documentation will need updating:
https://github.com/kinvolk/inspektor-gadget/blob/main/docs/guides/top/ebpf.md#a-note-about-memory-usage-of-maps

Using the values from fdinfo takes into account percpu maps, so that's an improvement but BPF_MAP_TYPE_PERF_EVENT_ARRAY maps will unfortunately still not account for the buffers in the map.

```
127: perf_event_array  name events  flags 0x0
	key 4B  value 4B  max_entries 4  memlock 4096B
	pids execsnoop(501155)
```
```
$ sudo cat /proc/501155/fdinfo/4
...
memlock:	4096
map_id:	127
```
