### ISSUE TITLE
Generate scaffolding for gadgets automatically

### ISSUE THREAD

**Issue by johananl** [inspektor-gadget/inspektor-gadget#982]
Adding a new gadget is currently far from trivial due to the many places one has to touch the codebase. We could add some automation for generating scaffolding for new gadgets so that all the user has to (hopefully) do is implement gadget logic in C and Go. The wiring of the various packages, registering Cobra commands etc. could all be automated.

We could probably go with something like `make new-gadget` with arguments indicating the gadget's name and type. The Make target would then generate C and Go code for the gadget with TODO comments in the areas which the developer has to implement.

**Comment by alban** [comment]
There could be a way to integrate the scaffolding from https://bumblebee.io/ instead of reinventing our own. There are [bumblebee examples](https://github.com/solo-io/bumblebee/tree/main/examples) for opensnoop, tcpconnect and others. We could need to define some convention for using IG's `containers` and `mount_ns_filter` maps. We could work on a gadget:
```
kubectl gadget bumblebee ghcr.io/solo-io/bumblebee/tcpconnect
```
And IG could reuse existing bumblebee eBPF packages from OCI registries.

**Comment by alban** [comment]
Proof of concept: https://github.com/inspektor-gadget/inspektor-gadget/pull/1151

**Comment by mauriciovasquezbernal** [comment]
We are all in for having [image-based gadgets](https://github.com/inspektor-gadget/inspektor-gadget/issues/1929), so I think this issue is not needed anymore.
